### ISSUE TITLE
BUG: Game.PrintMessage();

### ISSUE THREAD

**Issue by kivlara** [EnsageSharp/Ensage.Common#12]
Hi,

I try to:
```
Game.PrintMessage("<font face='Verdana' color='#ff7700'>TEST OK!</font>", MessageType.ChatMessage);
```

No message is show.
Other chat messages disappear.

**Comment by Moones** [comment]
Doesnt have to do anything with Common.
Make sure you use it while in-game.
If you will still not be able to make it work, make a thread in a dev section.
