### ISSUE TITLE
we can't use GetCastRange on units with inventory

### ISSUE THREAD

**Issue by Anzulo** [EnsageSharp/Ensage.Common#14]
Currently we cannot use `Ability.GetCastRange` if the owner is of type `Unit`. But we should be since there are units like lone druids bear which have a inventory and can use items.

Using GetCastRange is comfortable because it also checks for the aether lens range bonus. `ability.CastRange` works but does not contain the bonus range.

**Comment by Moones** [comment]
Hey, thanks for the report, I will look on that when i have time! :)

**Comment by Moones** [comment]
Should be fixed now
