### ISSUE TITLE
Building project

### ISSUE THREAD

**Issue by Rejjell** [EnsageSharp/Ensage.Common#21]
Hello. I'm trying to build this project in Monodevelop, but I'm getting errors such "The type or namespace name 'Hero' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (Ensage.Common)" for types Hero, Unit, etc. This is because Ensage and Ensage.Sandbox references are absent. Where can I find this dlls?

**Comment by Moones** [comment]
Hi, these are located in "PlaySharpLoader\System" folder.
You can also download the Ensage.Core manually from here: https://github.com/EnsageSharp/Ensage.Release/releases

**Comment by Rejjell** [comment]
Thanks for fast answer! The problem was solved.

**Comment by Moones** [comment]
np)
