### ISSUE TITLE
Compile Error.

### ISSUE THREAD

**Issue by MAkcanca** [EnsageSharp/Ensage.Common#22]
Done building target "ResolveAssemblyReferences" in project "Ensage.Common.csproj".
Target CoreResGen:
    Processing resource file "Properties\Resources.resx" into "obj\Release\Ensage.Common.Properties.Resources.resources".
Target GenerateTargetFrameworkMonikerAttribute:
  Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
Target CoreCompile:
    C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Csc.exe /noconfig /unsafe- /nowarn:1701,1702 /nostdlib+ /platform:x64 /errorreport:prompt /warn:4 /doc:bin\Release\Ensage.Common.xml /define:TRACE /highentropyva+ /reference:C:\Users\MAkcanca\Downloads\LeagueSharp\System\Ensage.dll /reference:C:\Users\MAkcanca\Downloads\LeagueSharp\System\EnsageSharp.Sandbox.dll /reference:C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll /reference:C:\Users\MAkcanca\Downloads\LeagueSharp\System\SharpDX.Direct3D9.dll /reference:C:\Users\MAkcanca\Downloads\LeagueSharp\System\SharpDX.dll /reference:C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll /reference:C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll /reference:C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll /reference:C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Extensions\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.Extensions.dll /reference:C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll /debug:pdbonly /filealign:512 /optimize+ /out:obj\Release\Ensage.Common.dll /subsystemversion:6.00 /resource:obj\Release\Ensage.Common.Properties.Resources.resources /target:library /utf8output AbilityInfo\AbilityDamage.cs Algorithm.cs DelayAction.cs Extensions\AbilityExtensions.cs Extensions\EntityExtensions.cs Extensions\EnumerableExtensions.cs Extensions\SharpDX\Generic.cs Extensions\SharpDX\Vector2Extensions.cs Extensions\SharpDX\Vector3Extensions.cs Extensions\SharpDX\Vector4Extensions.cs Geometry.cs HUDInfo.cs Objects\Abilities.cs Objects\Creeps.cs Objects\Heroes.cs Objects\JungleCamps.cs Events.cs Menu\Menu.cs Menu\MenuConfig.cs Menu\MenuUtils.cs Menu\MultiLanguage.cs Menu\NotificationData\INotification.cs Menu\NotificationData\Notification.cs Menu\Notifications.cs Objects\Names.cs Objects\Players.cs Orbwalking.cs AbilityInfo\AbilityInfo.cs AbilityInfo\AbilityDatabase.cs Properties\Resources.Designer.cs SideMessage.cs Signals\Signal.cs Signals\SignalManager.cs TargetSelector.cs UnitDatabase.cs Prediction.cs Properties\AssemblyInfo.cs Unit\AttackAnimationData.cs Unit\UnitInfo.cs Utils.cs Extensions\VectorExtensions.cs WindowsMessages.cs "C:\Users\MAkcanca\AppData\Local\Temp.NETFramework,Version=v4.5.2.AssemblyAttributes.cs"
    AbilityInfo\AbilityDatabase.cs(22,11): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
    AbilityInfo\AbilityDatabase.cs(23,11): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
    UnitDatabase.cs(25,11): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
    UnitDatabase.cs(26,11): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
Done building target "CoreCompile" in project "Ensage.Common.csproj" -- FAILED.

Done building project "Ensage.Common.csproj" -- FAILED.

Build FAILED.

C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Microsoft.Common.targets(983,5): warning MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
AbilityInfo\AbilityDatabase.cs(22,11): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
AbilityInfo\AbilityDatabase.cs(23,11): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
UnitDatabase.cs(25,11): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
UnitDatabase.cs(26,11): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
    2 Warning(s)
    4 Error(s)

Time Elapsed 00:00:00.37

**Comment by Moones** [comment]
hi you are missing .NET framework: http://go.microsoft.com/fwlink/?LinkId=528259
