### ISSUE TITLE
References Missing

### ISSUE THREAD

**Issue by gentmat** [EnsageSharp/Ensage.Common#39]
Ignore my ignorance i am a java Coder so c# is new for me . 
I was missing several libraries . SharpDX, SharpDx3d9,SharpDx.Xiinput ... Newtonsoft ( Fixed
Downloaded them via nuget and the references works perfectly now)

I am still missing "Ensage" and "EnsageSharp.Sandbox" Where to get these from ? 
Thank u

**Comment by Moones** [comment]
LoaderFolder\References
LoaderFolder\System

**Comment by gentmat** [comment]
sorry didnt get it . where is that LoaderFolder\References
LoaderFolder\System . i downloaded the zip but i cant find folder system or references

**Comment by Moones** [comment]
You have to install the loader first, you should specify the folder location during installation, then start loader atleast once and those folders will appear ;)

**Comment by gentmat** [comment]
install the loader first -- > where is that ?

**Comment by gentmat** [comment]
no answer :( . i cant figure it out

**Comment by gentmat** [comment]
I installed the loader , There is no ensage , Its leagueSharp . it have EnsageSharp.Sandbox but not Ensage.dll
Its like they deleted the loader for dota

**Comment by h3h3** [comment]
change Game Service to Ensage

**Comment by gentmat** [comment]
OMG ! thx a lot .

**Comment by Moones** [comment]
Glad you've figured it out, im closing the issue for now.
